name: Test App (telegramBot)
on:
  workflow_call:

jobs:
  build:
    strategy:
      matrix:
        platform: [ubuntu-latest, windows-latest, macos-latest]
        python-version: ["3.13", "3.14"]
    runs-on: ${{ matrix.platform }}

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies on Linux/MacOS
        if: runner.os != 'Windows'
        working-directory: telegramBot
        run: |
          python -m pip install --upgrade pip
          pip install flake8 pytest
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Install dependencies on Windows
        if: runner.os == 'Windows'
        working-directory: telegramBot
        run: |
          python -m pip install --upgrade pip
          pip install flake8 pytest
          if (Test-Path -Path "requirements.txt") { pip install -r requirements.txt }

      - name: Lint with flake8
        working-directory: telegramBot
        run: |
          # stop the build if there are Python syntax errors or undefined names
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
          # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
          flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

      - name: Run Tests
        run: |
          pytest telegramBot/tests/
